CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 OMP_NUM_THREADS=1 NCCL_P2P_DISABLE=1 torchrun --nproc_per_node 8 \
    --nnodes 1 \
    --node_rank 0 \
    --master_addr localhost \
    --master_port 29600 \
    ETrain/Train/LAVIS/train.py \
    --deepspeed ./scripts/zero3_offload.json \
    --lora_enable True --lora_r 64 --lora_alpha 256 \
    --cfg-path ./scripts/InstructBlip/instructblip.yaml \
    --bf16 True \
    --output_dir ./checkpoints/InstructBlip/CoIN/scienceqa \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 10000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --report_to none 